name: lint and type check

on:
  pull_request:
    branches:
      - feat/*
      - fix/*
      - test/*
      - main
  push:
    branches:
      - main
      - production

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.25

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun lint
    
      - name: Type check
        run: bun tsc --noEmit